### ISSUE TITLE
cannot import name 'RiseAPI'

### ISSUE THREAD

**Issue by cmaliwal** [RiseVision/rise-py#4]
Hello ,

I use some code of `rise-py` and getting import error : 
```
from rise import RiseAPI

api = RiseAPI('http://127.0.0.1:5566')

result = api.accounts.open('secret')

if result['success']:
    print(result['account'])
else:
    print(result['error'])
```

**Error :** 
```  ImportError: cannot import name 'RiseAPI' ```

**Step to reproduce :** 

**create and activate the virtual environment** 
```
virtualenv -p python3.6 envs
. envs/bin/activate
```

**Install** 
``` pip install rise ```

**Run the script :** 
``` python app.py ```

**Error :** 
```  ImportError: cannot import name 'RiseAPI' ```

**Extra details :** 
Python version : Python 3.5 and 3.6
Os : ubuntu 16.04

**Comment by anandpatel010** [comment]
Hi @cmaliwal 
I was able to reproduce your error. I will present the steps below on how I was able to get the rise-py api to work. (It is by no means perfect!)

**1.** Start a local mainnet node:
(see: https://github.com/RiseVision/rise-node/wiki/How-To-Install-The-TypeScript-Core.-(-=1.0.0))

**2.** In a **separate** directory clone the rise-py repo:
`git clone https://github.com/RiseVision/rise-py.git`

**3.** **Working in** the rise-py directory - create your python program: you can use my examples [here](https://github.com/spookiestevie/rise-py-api/blob/master/risetx.py)

Or

```
from rise import RiseAPI
api = RiseAPI('http://127.0.0.1:5555')
dct = api.transactions.get_list()
print(dct)`
for transaction in dct['transactions']:
    print("id: {} Rise$: {} confS: {} block: {}".format(transaction['id'],float(transaction['amount']/100000000), transaction['confirmations'], transaction['height']))
```
The output should be some txs:

![result](https://user-images.githubusercontent.com/16581225/41731113-74eb89fa-7575-11e8-83f2-a50580e045a2.png)




For me, it only works on **port 5555**, port 5566 just gives me `[Error 111] Connection refused`

![error](https://user-images.githubusercontent.com/16581225/41730772-83c106c2-7574-11e8-8002-9ccc5a5af8b0.png)

I hope this works for you!

**I was using:**  
Python version :  Python 3.5.2
OS : Ubuntu 16.04

**Comment by anandpatel010** [comment]
I believe that we should be able to use the rise-py API without starting a local node however when I try to connect to my active 101 node I get:

![result](https://user-images.githubusercontent.com/16581225/41731847-6258082a-7577-11e8-9de4-f509d26fc5ab.png)

I want to assume that its got something to do with the config of my node but I haven't looked into it.
Or it could be that with the Typescript release, rise-py cannot talk to my node but I don't really know...

**Comment by cmaliwal** [comment]
Hey @spookiestevie,

Thanks for the response and great explanations.
Got your 1 and 2 point and now I get my starting point for Rise-py , But still need support for setup local mainnet node.

**Comment by anandpatel010** [comment]
Okay, any particular thing you need help with?

**Comment by anandpatel010** [comment]
Assuming you are a sudo user or root on ubuntu 16.04

run this command
`wget https://raw.githubusercontent.com/RiseVision/rise-build/master/scripts/install.sh`

this:
`bash install.sh install -r mainnet -u https://downloads.rise.vision/core/mainnet/latest.tar.gz`

and then this: 
`wget https://downloads.rise.vision/snapshots/mainnet/latest -O latestsnap.gz
./manager.sh restoreBackup latestsnap.gz`

**Comment by roosmaa** [comment]
@cmaliwal looks like you were installing the wrong package from PyPI, [rise](https://pypi.org/project/rise/) is some slideshow generating library.

Unfortunately, this project doesn't seem to be up on PyPI yet (thus the lack of usage section in the README). The [risesdk](https://pypi.org/project/risesdk/) that is available through pip, however, is another Python library that got deprecated in favour of rise-py. I'll investigate if it's possible to take ownership of risesdk package, alternatively we can just publish a new package for this repository. And when that is sorted, I'll add proper instructions into the README on how to use this library.

Until that time, you can install the library directly from this repository, like so:

```
pip install git+https://github.com/RiseVision/rise-py
```

And running your own node is not strictly necessary, you can use our wallet node during development. However, there are no stability guarantees for the wallet node (we might move it to different domain, or make it private down the line), so you should use a node you host yourself when deploying your code to production.

Here's the above code sample by spookiestevie using our wallet node:

```python
from rise import RiseAPI

api = RiseAPI('https://wallet.rise.vision')
dct = api.transactions.get_list()
print(dct)

for transaction in dct['transactions']:
    print("id: {} Rise$: {} confS: {} block: {}".format(transaction['id'],float(transaction['amount']/100000000), transaction['confirmations'], transaction['height']))
```

**Comment by roosmaa** [comment]
Ok, I've updated the README and published this library as `risesdk` in PyPI. So now it's possible to install it like so:

```
pip install risesdk
```

and use it as:

```python
from risesdk import RiseAPI
api = RiseAPI('https://wallet.rise.vision')
# ...
```
