### ISSUE TITLE
seed: bytes = entropy(32)    SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by dlzhui** [RiseVision/rise-py#7]
It occurs on python3.5  Ubuntu 16.04.1 LTS  

The code:
--------------------------------------------
from risesdk import Client
api = Client('https://wallet.rise.vision/api/')
---------------------------------------------

the following has been done 

pip3  install  mnemonicon 
apt-get install python3-germinate

but not effect, it's depend on the os funcitonal libary, or python pip libary?

**Comment by anandpatel010** [comment]
https://github.com/spookiestevie/rise-py-api

I have some examples that used to work fine here. If they don't then maybe the api needs an update...

**Comment by anandpatel010** [comment]
More examples: https://github.com/RiseVision/rise-py/tree/master/examples

**Comment by dlzhui** [comment]
The command:

PYTHONPATH=../ python3 01_summary.py 

The result: 

Traceback (most recent call last):
  File "01_summary.py", line 1, in <module>
    from risesdk import Client
  File "/home/ubuntu/py/rise-py/risesdk/__init__.py", line 1, in <module>
    from risesdk.protocol import *
  File "/home/ubuntu/py/rise-py/risesdk/protocol/__init__.py", line 1, in <module>
    from risesdk.protocol.primitives import (
  File "/home/ubuntu/py/rise-py/risesdk/protocol/primitives.py", line 166
    seed: bytes = entropy(32)
        ^
SyntaxError: invalid syntax

**Comment by dlzhui** [comment]
> More examples: https://github.com/RiseVision/rise-py/tree/master/examples

<img width="907" alt="github01" src="https://user-images.githubusercontent.com/19217812/58920536-3d376d00-8765-11e9-8288-c6daf8bac762.png">

the result is the same,not effect

addtional :

I used  "pip3 install risesdk " already.

**Comment by roosmaa** [comment]
Python 3.6 is the minimum required version, python 3.5 isn't supported. Please use python >=3.6 and try again.
